int idusuario = 0;
String tipousuario = "";
String ubicacioncliente = "-17.7335177, -63.1256928";
String nombreusuarioautentificado = "";
String tipocliente = "cliente";
String tipobombero = "bombero";
String tipoambulancia = "ambulancia";
String tipopolicia = "policia";
String apoyo = "apoyo";
